### PR TITLE
v4.9.0

### PR DESCRIPTION
**Pull request by marcosaia1812**
### Version 4.9.0:
🎉 New:
- Brand new “Next Generation” machine-learning-based barcode scanning engine with improved reliability and much faster performance!
- API changes for the new barcode engine: added engineMode property of type EngineMode on barcode scanning APIs - `BarcodeScannerConfiguration` and `BatchBarcodeScannerConfiguration` to switch between the legacy barcode engine and the new Next Generation barcode engine. By default, the new engine is used.
- Text Data Scanner: a new RTU-UI component that allows you to perform OCR using our Data Scanner Camera API. See the new API function `startTextDataScanner`

🐞 Bug fixes:
- Document Scanner (Android): fixed a bug that sometimes caused pictures to have the wrong orientation after they were imported
- Fixed various UI related issues

🚙 Under the hood
- Updated the native Android Scanbot SDK to 1.85.1
- Updated the native iOS Scanbot SDK to 1.19.3

### CODE REVIEW

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by marcosaia1812** [comment]
run tests

**Pull request merged**
